name: activemigration
version: 0.2.1
author: Axel Christ <adracus@gmail.com>
description: A pub package
homepage: https://github.com/Adracus/ActiveMigration/tree/master
documentation: https://github.com/Adracus/ActiveMigration/tree/master
dependencies:
  activerecord: '>=2.3.0 <3.0.0'
  postgres_adapter: '>=0.0.8 <0.1.0'
  args: '>=0.11.0 <0.12.0'
  codewriter: '>=0.2.2 <0.3.0'
  path: '>=1.2.1 <1.3.0'
  postgresql: ">=0.2.14 <0.3.0"
  yaml: '>=0.1.0 <1.0.0'
