name: activemigration
version: 0.0.2
author: Axel Christ <adracus@gmail.com>
description: A pub package
homepage: https://github.com/Adracus/ActiveMigration/tree/master
documentation: https://github.com/Adracus/ActiveMigration/tree/master
dependencies:
  activerecord: ">=2.0.2 <3.0.0"
  postgres_adapter: ">=0.0.3 <0.1.0"
  yaml: ">=0.1.0 <1.0.0"
