name: activemigration
version: 0.0.2
author: Axel Christ <adracus@gmail.com>
description: A pub package
homepage: https://github.com/Adracus/ActiveMigration/tree/master
documentation: https://github.com/Adracus/ActiveMigration/tree/master
dependencies:
  activerecord:
    git: git://github.com/Adracus/ActiveRecord.git
    version: '>=2.0.2 <3.0.0'
  postgres_adapter:
    git: https://github.com/Adracus/PostgresAdapter.git
    version: '>=0.0.6 <0.1.0'
  yaml: '>=0.1.0 <1.0.0'
